import express from "express";
import notasController from "../controllers/notasController.js";
const router = express.Router();
router.get("/", notasController.getAll);
router.get("/:id", notasController.getById);
router.post("/", notasController.create);
router.put("/:id", notasController.update);
router.post("/:id", notasController.updateFavorito);
router.delete("/:id", notasController.delete);
export default router;
